### ISSUE TITLE
bug: oauth

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#32]
Dropbox and google drive login seems broken

**Comment by mickael-kerjean** [comment]
DONE

**Comment by immigrantsheep** [comment]
I can still see the dropbox and google drive broken logins. I installed nuage via docker-compose. Should I have just pulled the repo down instead?

**Comment by mickael-kerjean** [comment]
Hi there, Dropbox and Google drive requires some api keys to login. The how to do it is written  [here](https://github.com/mickael-kerjean/nuage/blob/master/config_server.js). Essentially:
```

// GOOGLE DRIVE
// 1) enable the api: https://console.developers.google.com/apis/api/drive.googleapis.com/overview
// 2) create credentials: https://console.developers.google.com/apis/credentials/oauthclient

// DROPBOX
// 1) create an third party app: https://www.dropbox.com/developers/apps/create
//    -> dropbox api -> "Full Dropbox" or "App folder" -> whatever name you want ->
//    -> set redirect URI to https://example.com/login ->
```

Let me know if there's any problem while creating the keys.

**Comment by mickael-kerjean** [comment]
Just to give you an example of the docker-compose file running on my server with a few adjustments to hide my api keys:
```
version: '2'
services:
  app:
    container_name: nuage
    image: machines/nuage
    restart: always
    mem_limit: 20GB
    environment:
    - SECRET_KEY=xxxxxxx
    - APPLICATION_URL=https://nuage.kerjean.me
    - GDRIVE_CLIENT_ID=xxxxxxxx
    - GDRIVE_CLIENT_SECRET=xxxxxx
    - DROPBOX_CLIENT_ID=xxxxxxx
    network_mode: bridge    
    ports:
    - "127.0.0.1:10006:8334"    

```

**Comment by immigrantsheep** [comment]
@mickael-kerjean this fixed it :) thank you for your help!
